class EcoModel < xeogl.Model
  def initialize(frame , id)
    super({id: id})
    @frame = frame
  end

  def update()
    self.components["floor_cube"].scale((@frame.width + 400)/2 , 10 , (@frame.length + 400)/2 )
    self.components["floor_cube"].position(0, -@frame.height - @frame.size , 0)
  end
end
