class Floor < EcoModel

  def initialize(data)
    super(data,  "floor")
    self.cube( "floor_cube" , "floor")
    self.update()
  end

  def update()
    self.at("floor_cube").scale((self.width + 400)/2 , self.size , (self.length + 400)/2 )
    self.at("floor_cube").position(0, -self.height - 3*self.size , 0)
    self.update_feet()
  end
  def update_feet()
    0.upto(self.posts - 1 ) do |i|
      self.update_foot1(i)
      self.update_foot2(i)
    end
    self.check_remove("foot1" + self.posts)
    self.check_remove("foot2" + self.posts)
  end
  def update_foot1(i)
    foot1 = self.for("foot1" + i)
    foot1.position(self.width/2  ,-self.height - self.size ,  self.offset(i))
    foot1.scale( self.size, self.size, self.size)
  end
  def update_foot2(i)
    foot2 = self.for("foot2" + i)
    foot2.position(-self.width/2 ,-self.height - self.size ,  self.offset(i))
    foot2.scale( self.size, self.size, self.size)
  end
end
