class FloorBeams < EcoModel

  def initialize(data)
    super(data,"floor_beams")
    self.update()
  end

  def joist_num
    Math.ceil(self.width / 60) + 1
  end
  def joist_spacing
    self.width / (joist_num - 1)
  end
  def update()
    self.update_list(self.joist_num , "joist")
    self.update_list(self.posts , "beam")
    self.update_pairs(1, "plate")
  end
  def update_joist(joist , i )
    joist.position(i*self.joist_spacing - self.width/2,
                    -self.height + self.size/2 + 15, 0 )
    joist.scale( 2.5, 15/2,  self.length / 2 )
  end
  def update_beam(beam , i)
    beam.position(0 ,  -self.height + self.size/2, self.offset(i) )
    beam.scale( self.width / 2, self.size / 2,  self.size / 2 )
  end
  def update_plate(plate , i ,  side)
    plate.position(side * self.width / 2 ,  - self.height + self.size/2,
                    self.offset(self.posts/2 - 0.5) )
    plate.scale( self.size / 2, self.size / 2,  self.length/2 )
  end
end
