class Floor < xeogl.Model
  def initialize(frame)
    super({})
    @frame = frame
    @floor = frame.cube_for(self , "floor")
    self.update()
  end

  def update()
    @floor.scale((@frame.width + 400)/2 , 10 , (@frame.length + 400)/2 )
    @floor.position(0, -@frame.height - @frame.size , 0)
  end
end
