class Floor < EcoModel

  def initialize(data)
    super(data,  "floor")
    self.cube( "floor_cube" , "floor")
    self.update()
  end

  def update()
    self.at("floor_cube").scale((self.width + 400)/2 , self.size , (self.length + 400)/2 )
    self.at("floor_cube").position(0, -self.height - 3*self.size , 0)
    self.update_feet()
  end
  def update_feet()
    self.update_pairs( self.posts , "foot" , "grey")
  end
  def update_foot(foot, i , side)
    foot.position(side * self.width/2  ,
                  -self.height - self.size ,  self.offset(i))
    foot.scale( self.size, self.size, self.size)
  end
end
