class Structure < EcoModel
  def initialize(name)
    super(VueController._data ,  "name")
    @parts = []
    @subparts = []
  end
  def subparts
    return @subparts
  end
  def add_part(name)
    p = name.new(@data)
    self.add( p )
    @parts << p.id
    p.parts().each {|pp|
      @subparts << pp
    }
  end
  def update( )
    0.upto(@data.level) do |i|
      next unless @subparts[i]
      @subparts[i].func.call()
    end
  end
  def invisible( )
    @parts.each do |p|
      self.components[p].iterate {|elem| elem.visible = false}
    end
  end
  def joins()
    sum = 0
    @parts.each { |p| sum = sum + self.components[p].joins() }
    return sum + @trusses[@data.truss].joins()
  end
  def pieces()
    sum = 0
    @parts.each { |p| sum = sum + self.components[p].pieces() }
    return sum + @trusses[@data.truss].pieces()
  end
  def lengths()
    sum = 0
    @parts.each { |p| sum = sum + self.components[p].lengths() }
    sum += @trusses[@data.truss].lengths()
    sum += self.pieces() * 0.2 #cracked ends
    # we use the lengths for scaling, which are half the real, and assume pairs
    sum *= 2 * 2
    return sum
  end
end

class House < Structure
  def initialize()
    super("house")
    [Floor,Post,Harja,FloorBeams,Walls,
        Slope,Tuuli,Space,Shell].each {|part| self.add_part(part)}
    self.update()
  end
end
class Frame < Structure
  def initialize()
    super("frame")
    [Floor,Post].each {|part| self.add_part(part)}
    @trusses = {  king: King.new(@data) ,
                  pulp: Pulpetti.new(@data),
                  collar: Collar.new(@data),
                  hammer: Hammer.new(@data),
                  stopped: Stopped.new(@data),
                  none: NoTruss.new(@data , "none")}
    self.set_truss(:king)
    self.update()
  end
  def set_truss(arg)
    if(arg == :pulp && @data.frame.angle > 15)
      @data.frame.angle = 10
    end
    if(arg != :pulp && @data.frame.angle < 15)
      @data.frame.angle = 30
    end
    @trusses.keys().each do |roof|
      @trusses[roof].iterate {|elem| elem.visible = false}
    end
    @trusses[arg].iterate {|elem| elem.visible = true}
  end
  def update()
    super()
    truss = @trusses[@data.truss]
    truss.parts().each {|pp|
      pp.func.call()
    }
  end
end
