class Plate < EcoModel

  def initialize(data)
    super(data,"plate")
    self.cubes(["plate1","plate2"])
    self.update()
  end

  def update()
    self.update_plate_at(self.at("plate1"), 1)
    self.update_plate_at(self.at("plate2") , -1)
  end

  def update_plate_at(plate , side)
    plate.position(side * self.width / 2 , -self.size/2 ,
      self.offset(@data.posts/2 - 0.5) )
    plate.scale( self.size / 2, self.size / 2,  self.spacing*(@data.posts-1)/2 )
  end

end
