class PostBeam
  def initialize( app , index , offset )
    @size = 15
    @height = 200
    @width = 300
    @braces = true
    @app = app
    @offset = offset
    @index = index
    self.add_post_at(@width/2)
    self.add_post_at(- @width/2)
    self.add_beam()
    self.add_brace(1)
    self.add_brace(-1)
  end
  def add_post_at(at)
    @post = @app.createCube()
    @post.position.set( at , -@height / 2 , @offset )
    @post.scale.set( @size / 2,@height / 2, @size/2)
    @post.material.set("color" , "salmon")
  end
  def add_beam()
    @beam = @app.createCube()
    @beam.position.set(0 , -@size/2 ,@offset)
    @beam.scale.set( @width / 2 + @size / 2,@size / 2,  @size/2 )
    @beam.material.set("color" , "salmon")
  end
  def add_brace(turn)
    @brace = @app.createCube()
    @brace.scale.set( @size / 2, 50, @size / 2)
    @brace.material.set("color" , "salmon")
    @brace.rotation.rotateZ(turn*Math.PI/4)
    @brace.position.set( turn*(@width/2 - 50 + @size ),
                          -50 + @size / 2, @offset )
  end
  def set_size(size)

  end
end
