class Pulpetti < EcoModel

  def initialize( data  )
    super(data)
  end

  def update()
    self.update_list(  self.posts , "king" )
    self.update_list(  self.posts , "rafter" )
  end
  def update_king(king,i)
    truss_height = self.tan * self.width
    king.position( -self.width/2 , truss_height/2, self.offset(i) )
    king.scale( self.size / 2,truss_height / 2,  self.size/2 )
  end
  def update_rafter(rafter , i , side)
    rafter.rotateZ( (90 - self.angle)  )
    rafter.position( ( self.cos*self.size)/4  ,
                        self.tan*self.width/2 - self.cos*self.size/2  ,
                        self.offset(i))
    rafter.scale( self.size / 2, self.rafter_length/2 + 70 ,  self.size/ 2 )
  end
  def brace_rad
    return 45* Math.PI / 180
  end
  def brace_sin
    return Math.sin(self.brace_rad)
  end
  def brace_sinm
    return Math.sin(Math.PI/2 - self.brace_rad)
  end
  def brace_cosm
    return Math.cos(Math.PI/2 - self.brace_rad)
  end
  def brace_length
    return  self.sin * self.width / 4 - self.size/2
  end
  def rafter_length
    return self.width/ self.cos
  end

end
