class Pulpetti < xeogl.Model

def initialize( frame  )
  super({})
  @frame =  frame
  @king = frame.cube_for(self)
  @rafter = frame.cube_for(self)
end

def update()
  truss_height = @frame.tan * @frame.width
  @king.position( -@frame.width/2 , truss_height/2, 0 )
  @king.scale( @frame.size / 2,truss_height / 2,  @frame.size/2 )
  @rafter.rotateZ( (90 - @frame.angle)  )
  @rafter.position( ( @frame.cos*@frame.size)/4  ,
                      @frame.tan*@frame.width/2 - @frame.cos*@frame.size/2  ,
                      0)
  @rafter.scale( @frame.size / 2, self.rafter_length/2 + 70 ,  @frame.size/ 2 )
end
def brace_rad
  return 45* Math.PI / 180
end
def brace_sin
  return Math.sin(self.brace_rad)
end
def brace_sinm
  return Math.sin(Math.PI/2 - self.brace_rad)
end
def brace_cosm
  return Math.cos(Math.PI/2 - self.brace_rad)
end
def brace_length
  return  @frame.sin * @frame.width / 4 - @frame.size/2
end
def rafter_length
  return @frame.width/ @frame.cos
end
def remove_parts()
  scene.remove(@rafter)
  scene.remove(@king)
end

end
