class Frame < EcoModel
  def initialize()
    super(VueController._data ,  "frame")
    @trusses = Harja.new(@data)
    @truss = :harja
    self.add(PostBeam.new(@data , true))
    self.add(Floor.new(@data ))
    self.add(FloorBeams.new(@data ))
    self.add(Plate.new(@data ))
    self.add(Walls.new(@data ))
    self.add(Slope.new(@data ))
    self.add(Tuuli.new(@data ))
    self.add(Space.new(@data ))
    self.add(Shell.new(@data ))
    self.update()
  end
  def set_brace(on)
    @posts.set_brace(on)
  end
  def set_truss(arg)
    if(arg == :pulp && @data.frame.angle > 15)
      @data.frame.angle = 10
    end
    if(arg == :harja && @data.frame.angle < 15)
      @data.frame.angle = 30
    end
    @truss = arg
    @trusses.iterate {|elem| elem.visible = false}
    @trusses = Harja.new(@data ) if @truss == :harja
    @trusses = Pulpetti.new(@data ) if @truss == :pulp
    @trusses = NoTruss.new(@data) if @truss == :none
    self.update()
  end
  def update( )
    @trusses.update()
    self.components["posts"].update()
    self.components["plates"].update()
    self.components["floor"].update()
    self.components["floor_beams"].update()
    self.components["walls"].update()
    self.components["slope"].update()
    self.components["tuuli"].update()
    #self.components["space"].update()
    #self.components["shell"].update()
  end
end
