class Plate < EcoModel

  def initialize(data)
    super(data,"plates")
  end

  def update()
    self.update_pairs(1, "plate")
  end

  def update_plate(plate , index , side)
    plate.position(side * (self.width - self.size) , -self.size ,
                  self.offset(self.posts/2 - 0.5) )
    plate.scale( self.size, self.size,  self.spacing*(@data.posts-1)/2 )
  end

end
