class PostBeam < EcoModel
  def initialize( data   , braced )
    super(data, "posts")
    @braced = braced
  end
  def update()
    self.update_pairs( self.posts , "foot" , "grey")
    self.update_pairs(self.posts ,"post")
    self.update_list(self.posts ,"beam")
    self.update_pairs(self.posts ,"brace")
  end
  def update_foot(foot, i , side)
    foot.b_scale( side , 2*self.size, 2*self.size, 2*self.size)
    foot.trans(side*(self.width + self.size),
                  -2*self.height - 4*self.size ,  self.offset(i) + self.size)
  end
  def update_beam(beam , i)
    beam.b_scale(1,self.size, self.width, self.size)
    beam.rotZ(90)
    beam.trans(self.width , 0 ,self.offset(i))
  end
  def update_post(post , i, side)
    post.b_scale( -side , self.size, self.height , self.size)
    post.rotZ(180)
    post.trans(side * self.width , 0 , self.offset(i))
  end
  def update_brace( brace , i, side )
    brace.visible = @braced
    brace.b_scale(-side,self.size, self.brace_size, self.size)
    brace.rotZ(side*45)
    brace.trans(side*( self.width - 2*self.size),
                      -2*self.brace_size/1.41 - 2*self.size ,
                       self.offset(i))
  end
  def braces
    return @braced
  end
  def set_brace(on)
    @braced = on
  end
  def brace_size
    size = Math.min(self.width , self.height)
    return Math.max(size / 3 , 50)
  end
end
