class Pulpetti < EcoModel

  def initialize( data  )
    super(data)
  end

  def update()
    self.update_list(  self.posts , "king" )
    self.update_list(  self.posts , "rafter" )
  end
  def update_king(king,i)
    truss_height = self.tan * self.width
    king.position( -self.width + self.size, truss_height, self.offset(i) + self.size)
    king.scale( self.size,truss_height,  self.size )
  end
  def update_rafter(rafter , i , side)
    rafter.rotateZ( (90 - self.angle)  )
    rafter.position( self.cos*self.size,
                     self.tan*self.width - self.cos*self.size + self.size ,
                     self.offset(i) + self.size)
    rafter.scale( self.size, self.rafter_length + 70 ,  self.size )
  end
  def brace_rad
    return 45* Math.PI / 180
  end
  def brace_sin
    return Math.sin(self.brace_rad)
  end
  def brace_sinm
    return Math.sin(Math.PI/2 - self.brace_rad)
  end
  def brace_cosm
    return Math.cos(Math.PI/2 - self.brace_rad)
  end
  def brace_length
    return  self.sin * self.width / 2 - self.size
  end
  def rafter_length
    return self.width/ self.cos
  end

end
