class Walls < EcoModel

  def initialize(data)
    super(data,"walls")
    self.update()
  end

  def wall_length
    return self.length + self.size - self.two_inch
  end
  def wall_num
    Math.ceil(self.wall_length / 60) + 1
  end
  def wall_spacing
    self.wall_length / (wall_num - 1)
  end
  def wall_offset(i)
    return self.wall_spacing * ((self.wall_num - 1)/2 - i)
  end
  def update()
    self.update_pairs(self.wall_num, "inner")
    self.update_pairs(self.wall_num, "outer")
    self.update_pairs(self.wall_num, "tie1")
    self.update_pairs(self.wall_num, "tie2")
    self.update_pairs(self.wall_num, "tie3")
  end

  def update_tie1(tie , i , side) self.update_tie(tie , i , side , 1);end
  def update_tie2(tie , i , side) self.update_tie(tie , i , side , 2);end
  def update_tie3(tie , i , side) self.update_tie(tie , i , side , 3);end

  def update_tie(tie , i , side , num)
    tie.position(side * (self.width_2 + self.size_2 + self.wall_ins_2 + self.one_inch) ,
                  (1 - num) * 80 - self.one_inch,
                  self.wall_offset(i) )
    tie.scale( self.wall_ins_2, self.one_inch , self.one_inch)
  end

  def update_inner(post , i , side)
    post.position(side * (self.width_2 + self.size_2) , -self.height_2 ,
                  self.wall_offset(i) )
    post.scale( self.one_inch, self.height_2 , self.one_inch)
  end
  def update_outer(post , i , side)
    post.position(side * (self.width_2 + self.size_2 + self.wall_ins) , -self.height_2 ,
                  self.wall_offset(i))
    post.scale( self.one_inch, self.height_2 , self.one_inch)
  end

end
